Command widget
mjkillough/cnx pull request #57
Opened 2023-01-23 07:12 UTC by thled

This adds a new widget `command` to `cnx-contrib`.

It shows the stdout of a configured cli command.

Example for `cnx-bin/src/main.rs`:

```rust
let command = command::Command::new(attr.clone(), "date".into());
cnx.add_widget(command);
```

2023-01-23 07:25 UTC, psibi requested changes
LGTM, apart from a minor comment.

2023-01-23 07:25 UTC, psibi commented on cnx-contrib/src/widgets/command.rs
> +        let ten_seconds = Duration::from_secs(10);
Can the ten seconds be configurable ?

2023-01-23 17:25 UTC, thled commented on cnx-contrib/src/widgets/command.rs
> +        let ten_seconds = Duration::from_secs(10);
Yes, done

2023-01-25 09:21 UTC, merged

2023-01-25 09:21 UTC, psibi commented
Thank you!